from typing import TypedDict, List, Dict, Any

class RoadmapState(TypedDict):
    # Raw text extracted from the PDF
    report_content: str
    # Processed list of skills found in the report
    skills_to_learn: List[str]
    # The final JSON roadmap generated by the AI
    final_roadmap_json: Dict[str, Any]